name: Auto-merge to target repository

on:
  push:
    branches:
      - dev  # Гілка, за якою потрібно слідкувати

jobs:
  merge_job:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонуйте вихідний репозиторій
      - name: Checkout source repository
        uses: actions/checkout@v3

      # Крок 2: Налаштуйте Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

      # Крок 3: Додайте цільовий репозиторій як віддалений
      - name: Add target repository
        run: |
          git remote add target-repo https://$GITHUB_ACTOR:${{secrets.REPO_ACCESS_TOKEN_3}}@github.com/milk-2-dev/fuel-price-dev.git
          git fetch target-repo

      # Крок 4: Перемикання на main гілку цільового репозиторію
      - name: Checkout main branch of target repository
        run: |
          git checkout target-repo/main

      # Крок 5: Злиття змін із вихідної гілки
      - name: Merge changes
        run: |
          git merge --no-ff origin/dev --allow-unrelated-histories
          git push target-repo main
